const fs = require('fs');
const file = 'c:/岛屿/qiutsmoke/app/api/generate-reminder/route.ts';
let code = fs.readFileSync(file, 'utf8');

code = code.replace(
  '        const body = await req.json();\n        const { mood, mode, elapsedTime, totalTime, sessionPhase = "middle", history = [], userAction, practiceCount = 0, diagnosisProfile = "" } = body;',
  '        const body = await req.json();\n        const { mood, mode, elapsedTime, totalTime, sessionPhase = "middle", history = [], userAction, practiceCount = 0, diagnosisProfile = "", customSystemPrompt } = body;'
);

code = code.replace(
  '            if (elapsedTime <= 40) {\n                rainStage = "【第0阶段：D - Diagnosis 诊断与上板】";\n                rainCommand = "引导用户稳住呼吸，面对即将袭来的烟瘾/欲望海浪。用冲浪的意象，告诉他们不要逃避，站在冲浪板上准备迎接冲击。";\n            } else if (elapsedTime <= 180) {\n                rainStage = "【第1阶段：R - Recognize 识别与认出】";\n                rainCommand = "让用户仅仅去“认出”烟瘾的存在。像是在海浪中看清浪花，承认身体里渴望多巴胺的冲动，不对抗，只是在心里默念“这只是一波想要抽烟的冲动”。";\n            } else if (elapsedTime <= 300) {\n                rainStage = "【第2阶段：A - Allow 接纳与允许】";\n                rainCommand = "告诉用户让海浪穿过自己。烟瘾是不舒服的，但允许这种不适感存在。不要去压抑、也不要去满足它。把它看作海上的风暴，你只需站在原地的冲浪板上。";\n            } else if (elapsedTime <= 600) {\n                rainStage = "【第3阶段：I - Investigate 好奇探究】";\n                rainCommand = "像科学家一样好奇地观察身体。问他们：烟瘾来临时，身体的哪里最难受？是胸口的紧缩，还是喉咙的干渴？把注意力放在那种物理感受上，而不是去想烟。";\n            } else {\n                rainStage = "【第4阶段：N - Note 标记与觉察 (非认同)】";\n                rainCommand = "提醒用户：你不是你的烟瘾。这股海浪正在消退。仅仅去标记此刻残留的感觉。即使下一波再来，你也有能力再次稳稳站住。";\n            }\n\n            systemPrompt = `# 交互背景与视觉形式\n这是一场针对戒断反应（如戒断烟瘾、网瘾等）的“欲望冲浪”急救指引。\n【当前阶段】：${rainStage}，历时 ${elapsedTime} 秒\n【临床情报】：${diagnosisProfile || "无"}\n\n# 你的任务\n严格遵循 Judson Brewer 博士的 RAIN 正念成瘾戒断模型。\n【本阶段操作手册】：${rainCommand}\n\n# 铁律约束\n1. 你的回复必须且只能是一句不超过30字的短句指导语，**直接输出文本**，绝对不要输出任何标签、格式或多余解释。\n2. 语言风格必须像一位冷酷、专业、充满力量的冲浪教练。\n3. 必须贯穿“冲浪（Urge Surfing）”意象（如：海浪、冲浪板、风暴、水面）。绝不要用拔河、怪兽等比喻。\n4. 绝对不可直接说出“烟”、“抽烟”这类触发词。用“海浪”、“冲动”、“极度的渴望”来指代烟瘾。\n5. 每次发话只针对当前时间阶段，绝不复读上一句。`;',
  '            if (elapsedTime <= 40) {\n                rainStage = "【第0阶段：D - Diagnosis 诊断与上板】";\n                rainCommand = "引导用户稳住呼吸，面对即将袭来的欲望海浪。用冲浪的意象，告诉他们不要逃避，站在冲浪板上准备迎接冲击。";\n            } else if (elapsedTime <= 180) {\n                rainStage = "【第1阶段：R - Recognize 识别与认出】";\n                rainCommand = "让用户仅仅去“认出”欲望的存在。像是在海浪中看清浪花，承认身体里渴望多巴胺的冲动，不对抗，只是在心里默念“这只是一波冲动”。";\n            } else if (elapsedTime <= 300) {\n                rainStage = "【第2阶段：A - Allow 接纳与允许】";\n                rainCommand = "告诉用户让海浪穿过自己。欲望是不舒服的，但允许这种不适感存在。不要去压抑、也不要去满足它。把它看作海上的风暴，你只需站在原地的冲浪板上。";\n            } else if (elapsedTime <= 600) {\n                rainStage = "【第3阶段：I - Investigate 好奇探究】";\n                rainCommand = "像科学家一样好奇地观察身体。问他们：欲望来临时，身体的哪里最难受？是胸口的紧缩，还是喉咙的干渴？把注意力放在那种物理感受上。";\n            } else {\n                rainStage = "【第4阶段：N - Note 标记与觉察 (非认同)】";\n                rainCommand = "提醒用户：你不是你的欲望。这股海浪正在消退。仅仅去标记此刻残留的感觉。即使下一波再来，你也有能力再次稳稳站住。";\n            }\n\n            const DEFAULT_SURF_SYSTEM_PROMPT = `你是一位冷酷、专业、充满力量的冲浪教练。这是一场针对戒断反应（如戒断烟瘾、网瘾等）的“欲望冲浪”急救指引。\n\n# 铁律约束\n1. 你的回复必须且只能是一句不超过30字的短句指导语，**直接输出文本**，绝对不要输出任何标签、格式或多余解释。\n2. 语言风格必须像一位冷酷、专业、充满力量的冲浪教练。\n3. 必须贯穿“冲浪（Urge Surfing）”意象（如：海浪、冲浪板、风暴、水面）。绝不要用拔河、怪兽等比喻。\n4. 绝对不可直接说出“烟”、“抽烟”这类触发词。用“海浪”、“冲动”、“极度的渴望”来指代烟瘾。\n5. 每次发话只针对当前时间阶段，绝不复读上一句。`;\n\n            systemPrompt = customSystemPrompt || DEFAULT_SURF_SYSTEM_PROMPT;'
);

code = code.replace(
  '        if (mode === \'urge_surfing\') {\n            // For Urge Surfing, we explicitly run a STATELESS architecture to prevent cross-stage contamination.\n            messages = [ { role: "system", content: systemPrompt } ];\n            \n            if (userAction) {\n                messages.push({\n                    role: "user",\n                    content: `【主动觉察报告】用户当前感受："${userAction}"\\n请严格根据当前《阶段手册》回应。不要超过30个字。`\n                });\n            } else {\n                messages.push({ \n                    role: "user", \n                    content: `时间到了第 ${elapsedTime} 秒，冲浪仍在继续。请给出当下的教练指引。不要超过30个字。` \n                });\n            }\n        } else {',
  '        if (mode === \'urge_surfing\') {\n            // For Urge Surfing, we explicitly run a STATELESS architecture to prevent cross-stage contamination.\n            let userContent = `【临床情报】：${diagnosisProfile || "无"}\\n\\n`;\n            userContent += `【当前阶段】：${rainStage}，历时 ${elapsedTime} 秒\\n`;\n            userContent += `【本阶段教练操作手册】：${rainCommand}\\n\\n`;\n            \n            if (userAction) {\n                userContent += `【主动觉察报告】用户当前感受："${userAction}"\\n请严格根据上述《教练操作手册》给出一句回应。不要超过30个字。`;\n            } else {\n                userContent += `时间到了第 ${elapsedTime} 秒，冲浪仍在继续。请严格根据上述《教练操作手册》给出一句指导。不要超过30个字。`;\n            }\n\n            messages = [\n                { role: "system", content: systemPrompt },\n                { role: "user", content: userContent }\n            ];\n        } else {'
);

fs.writeFileSync(file, code);
console.log("Updated route.ts");
